#ifndef LC_PROT_LCFU___COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_STRFROMBYTEARR_C__H
#define LC_PROT_LCFU___COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_STRFROMBYTEARR_C__H

#include <LC3CGBase.h>

/*                            Typedefs                         */
typedef struct _LC_TD_Function_COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_STRFROMBYTEARR_C
{
  LC_TD_BOOL LC_VD_ENO;
  LcCgChar LC_VD_FUN_LC_STRFROMBYTEARR_C[1025];
} LCCG_StructAttrib LC_TD_Function_COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_STRFROMBYTEARR_C;

/*                   ColdBoot Initialization Macro             */
#define LC_INIT_Function_COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_STRFROMBYTEARR_C(p) \
{ \
  LC_INIT_SIZED_STRING(&((p)->LC_VD_FUN_LC_STRFROMBYTEARR_C)); \
}

/*                            Prototype                        */
void  lcfu___COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_STRFROMBYTEARR_C(LC_TD_Function_COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_STRFROMBYTEARR_C* LC_this, LC_TD_BYTE LC_VD_VIB_ARR[1024], LC_TD_DINT LC_VD_VIDI_LEN, struct _lcoplck_epdb_1_impl* pEPDB);


#endif
