#ifndef LC_PROT_LCFU___COMx2ELOGICALSx2EBASICx2EDATETIMEx2EFUN_LC_WRITE_LOCALTIME_C__H
#define LC_PROT_LCFU___COMx2ELOGICALSx2EBASICx2EDATETIMEx2EFUN_LC_WRITE_LOCALTIME_C__H

#include <LC3CGBase.h>

/*                            Typedefs                         */
typedef struct _LC_TD_Function_COMx2ELOGICALSx2EBASICx2EDATETIMEx2EFUN_LC_WRITE_LOCALTIME_C
{
  LC_TD_BOOL LC_VD_ENO;
  LC_TD_INT LC_VD_VOI_ERR;
} LCCG_StructAttrib LC_TD_Function_COMx2ELOGICALSx2EBASICx2EDATETIMEx2EFUN_LC_WRITE_LOCALTIME_C;

/*                   ColdBoot Initialization Macro             */
#define LC_INIT_Function_COMx2ELOGICALSx2EBASICx2EDATETIMEx2EFUN_LC_WRITE_LOCALTIME_C(p) \
{ \
  LC_INIT_INT(&((p)->LC_VD_VOI_ERR)); \
}

/*                            Prototype                        */
void  lcfu___COMx2ELOGICALSx2EBASICx2EDATETIMEx2EFUN_LC_WRITE_LOCALTIME_C(LC_TD_Function_COMx2ELOGICALSx2EBASICx2EDATETIMEx2EFUN_LC_WRITE_LOCALTIME_C* LC_this, LC_TD_DINT LC_VD_SEC, LC_TD_DINT LC_VD_MIN, LC_TD_DINT LC_VD_HOUR, LC_TD_DINT LC_VD_DAY, LC_TD_DINT LC_VD_MONTH, LC_TD_DINT LC_VD_YEAR, struct _lcoplck_epdb_1_impl* pEPDB);


#endif
