#ifndef LC_PROT_LCFU___COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_BYTEARRFROMSTR_C__H
#define LC_PROT_LCFU___COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_BYTEARRFROMSTR_C__H

#include <LC3CGBase.h>

/*                            Typedefs                         */
typedef struct _LC_TD_Function_COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_BYTEARRFROMSTR_C
{
  LC_TD_BOOL LC_VD_ENO;
  LC_TD_BYTE LC_VD_FUN_LC_BYTEARRFROMSTR_C[1024];
} LCCG_StructAttrib LC_TD_Function_COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_BYTEARRFROMSTR_C;

/*                   ColdBoot Initialization Macro             */
#define LC_INIT_Function_COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_BYTEARRFROMSTR_C(p) \
{ \
  LC_INIT_ARRAY(&((p)->LC_VD_FUN_LC_BYTEARRFROMSTR_C),BYTE,1024); \
}

/*                            Prototype                        */
void  lcfu___COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_BYTEARRFROMSTR_C(LC_TD_Function_COMx2ELOGICALSx2EBASICx2ECONVERTx2EFUN_LC_BYTEARRFROMSTR_C* LC_this, LcCgChar LC_VD_VISTR_ARR[1025], LC_TD_DINT LC_VD_VIDI_LEN, struct _lcoplck_epdb_1_impl* pEPDB);


#endif
